"""add unique constraint on city name and country

Revision ID: 1176627ceaca
Revises: 8375e22f977a
Create Date: 2026-08-18 01:36:27.096631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1176627ceaca'
down_revision: Union[str, Sequence[str], None] = '8375e22f977a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_city_name_country', 'cities', ['name', 'country'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_city_name_country', 'cities', type_='unique')
    # ### end Alembic commands ###
