"""add raw_air_quality and raw_weather tables

Revision ID: 8375e22f977a
Revises: 720ba744baa4
Create Date: 2026-08-18 01:17:31.260788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8375e22f977a'
down_revision: Union[str, Sequence[str], None] = '720ba744baa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('pm25', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pm10', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('no2', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('o3', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'source', 'recorded_at', name='uq_air_quality_reading')
    )
    op.create_table('raw_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_direction', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pressure', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'recorded_at', name='uq_weather_reading')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_weather')
    op.drop_table('raw_air_quality')
    # ### end Alembic commands ###
